### ISSUE TITLE
Audio Imbalances and Other issues

### ISSUE THREAD

**Issue by Chinguuuu** [UnJust1ce/Mixtape#5] opened 2023-05-29 20:31 UTC
In my experience, in the Mixtape mod settings, under the Game tab, adjusting the values of the volume does not change anything. Also, I'm using More C418 Music by Spleenczar as well. This music seems to be much louder than the vanilla for some reason. I'm not sure if this is a Mixtape issue but I thought I would post it here.

Finally, I rarely ever hear the creative music in survival since I turned that setting on. Is it really that rare, or is there an issue with Mixtape?

**Comment by AliahX** [comment] 2023-05-29 21:27
Thanks for letting me know! I'll look into it after I fix another bug. And yeah the non-vanilla music was originally a different volume and I had to edit them to make them fit in with the vanilla sounds, i guess i'll look over them again, but i thought i had done well enough. I'm not sure what you mean C418 music by Spleenczar. And for the creative music playing in survival, the survival music already plays in creative so i had just set it to play the creative music set in survival and its worked for me previously but i'll also check on that. Thanks for letting me know!
If you wanna talk a bit easier you could join my discord server (https://discord.gg/WyrTsYFweK)

**Comment by AliahX** [comment] 2023-06-05 21:27
I can confirm that the creative music option is working as intended. Also if you use mixtape you won't need to use More C418 Music by Spleenczar because mixtape adds built in resourcepacks that also adds the same c418 music, but at the same volume as regular mc music.

**Comment by Chinguuuu** [comment] 2023-06-05 22:14
I would but I only use More C418 Music pack because I can delete certain tracks. Is there a way I can access the built in music packs from Mixtape and remove certain songs? Maybe that pack is also interfering with the creative mode music, so if I can swap, I would love to!

**Comment by AliahX** [comment] 2023-06-05 22:19
Which tracks are you deleting? mixtape adds multiple built in packs (one of them removes the newer music and adds the unused music)

**Comment by Chinguuuu** [comment] 2023-06-05 22:29
I understand Mixtape has those packs but since I have access to the other pack and the ability to delete various songs within it, I use that. I delete some of the unused songs within the pack. I can't find a way to remove the songs from your packs and also, your packs don't include the track Droopy Likes Richochet, which I like. Does that make sense? Otherwise, I would use your pack that removes the newer music but adds some unused music.

**Comment by AliahX** [comment] 2023-06-05 22:56
Which tracks are you deleting? I can make a version of the resourcepack that doesn't add all the unused songs, and where is droopy likes richochet used? I might also be able to add that.

**Comment by Chinguuuu** [comment] 2023-06-05 23:12
Oh but I wouldn't want you to publish an entire new pack just for my personal taste! If it isn't possible to customise your packs then I can continue using my current set-up. Although I will link the tracks I'm currently using that are included within More C418 Pack. 

![image](https://github.com/AliahX/Mixtape/assets/132147202/839588e3-cdc1-46b1-bead-21e7d6486bd3)

![image](https://github.com/AliahX/Mixtape/assets/132147202/71af3c69-cc03-4303-8086-06d17281be8f)

Droopy likes Richochet is from the Minecraft Volume Alpha. If it isn't possible to modify your music packs, then please consider this issue closed, I can continue to use my current set-up:)

**Comment by AliahX** [comment] 2023-06-06 01:13
I meant to ask if you had droopy playing as a disc or just ambience music. Also I managed to fix the first issue about the music not changing volume with the slider

**Comment by Chinguuuu** [comment] 2023-06-06 01:39
Oh it's ambient music. And great to hear about the fix:)

**Comment by Chinguuuu** [comment] 2023-06-07 17:03
I was also wondering if it would be possible to make a pack that allows the main menu music to be played in the overworld within one of your packs like the No Caves and Cliffs pack? Just the idea of getting as much C418 music in the overworld, specifically non-biome specific, as possible. Thank you for your time:)

**Comment by AliahX** [comment] 2023-06-07 19:20
Definitely! I have already made a non-biome specific resource pack that will be added in the next release (coming within a week hopefully)

**Comment by AliahX** [comment] 2023-06-08 02:10
Fixed in v1.5.0

**Closed as completed by AliahX** 2023-06-08 02:10 UTC
